# -*- coding: utf-8 -*-
"""h2.1.4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VG4GweXpWBMdNvrjK6-kSTgLWVbRCOva
"""

#2.1.4
def debug_control(*a, **e):
  b = 0
  c = 0
  d = 0 
  for i in a:
    if type (i) is str:
      b += 1
    elif type (i) is int:
      c += 1
    elif type (i) is float:
      d += 1
  for i in e:
    if type (i) is str:
      b += 1
    elif type (i) is int:
      c += 1
    elif type (i) is float:
      d += 1
  print("Str:", b, "Int:", c, "Float:", d)
debug_control("Hello!", 1000, 7, 993.0, name="Petr", task="Eliminate")