# -*- coding: utf-8 -*-
"""h2.1.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VG4GweXpWBMdNvrjK6-kSTgLWVbRCOva
"""

#2.1.3
def debug_control(*b):
  a = 0
  for i in b:
    a += 1
  return(a)
debug_control("Hello!", 1000, 7)