# -*- coding: utf-8 -*-
"""h2.1.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kBu83cc2DMpjcp7ZSlGqmXKEnqjSJz50
"""

#2.1.2
a = input().split()
b = []
c = []
def summation(a):
  for i in a:
    i = int(i)
    if i<0:
      b.append(i*-2)
    else:
      b.append(i)
  high = max(b)
  for i in b:
    i = int(i)
    c.append(i/high)
  summa = sum(c)
  print(summa)
summation(a)