# -*- coding: utf-8 -*-
"""h2.1.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LM1TvNtymMX9HCkbRwglNv9wKafIkYli
"""

#2.1.1
def greetings(a):
  a = input().split()
  g = "Доброго времени суток, "+ a[0] +' "Человек" ' + a[1] + "!"
  return g
greetings(a)