# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1woUYOP_92hUGUkh8vMKb6sWoyAs8gZGh
"""

a = input()
if len(a)>5:
  print(a[3], a[5])
else:
  print(a[::-2])