# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1woUYOP_92hUGUkh8vMKb6sWoyAs8gZGh
"""

a = input().split()
a = a[::-1]
a