# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1woUYOP_92hUGUkh8vMKb6sWoyAs8gZGh
"""

a = input().split()
b = int(a[0])
c = int(a[0])
for i in a:
  i = int(i)
  if b<i:
    b=i
  elif c>i:
    c=i
print(c, b)