# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qJHeNV1GiwezFmpD_GZiePgvxv1wVMf-
"""

a = input()
l = len(a)
k = 0
t = 0
i = 0
while k < l:
  if a[i].isupper():
    f = a[i]
    n = i
  if a[i].isdigit():
    t = a[i]
    g = a[i+1]
    n1 = i+1
    n2 = n1 - n 
    break
  k += 1
  i += 1
b = a[n::n2]
print(b)